name: Build Docker

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "${{secrets.HUB_DOCKER_USERNAME}}" --password-stdin
        docker image build -t ${{secrets.HUB_DOCKER_USERNAME}}/${{secrets.HUB_DOCKER_REPO_NAME}}:latest .
        docker push ${{secrets.HUB_DOCKER_USERNAME}}/${{secrets.HUB_DOCKER_REPO_NAME}}:latest
